package Admin;

import Connection.MyConnection;
import Login.LoginForm;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import javax.swing.JPanel;



public class Home extends javax.swing.JFrame {


    public Home() {
        initComponents();

        
        
        
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        DisplayUserLogin = new javax.swing.JLabel();
        ItemsPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        ItemsIcon = new javax.swing.JLabel();
        LogoutPanel = new javax.swing.JPanel();
        LogoutIcon = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        AddItemPanel = new javax.swing.JPanel();
        AddItemIcon = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        UserManagementPanel = new javax.swing.JPanel();
        UserManagementIcon = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setMinimumSize(new java.awt.Dimension(860, 600));
        MainPanel.setPreferredSize(new java.awt.Dimension(854, 600));
        MainPanel.setVerifyInputWhenFocusTarget(false);

        HeaderPanel.setBackground(new java.awt.Color(180, 16, 16));
        HeaderPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderPanelMouseDragged(evt);
            }
        });
        HeaderPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderPanelMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Warehouse Management System");

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Los Baños Centtromall");

        DisplayUserLogin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        DisplayUserLogin.setForeground(new java.awt.Color(255, 255, 255));
        DisplayUserLogin.setText("Logged In as: Admin");
        DisplayUserLogin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HeaderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(398, 398, 398)
                        .addComponent(DisplayUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HeaderPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(DisplayUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        ItemsPanel.setBackground(java.awt.SystemColor.controlHighlight);
        ItemsPanel.setMaximumSize(new java.awt.Dimension(140, 120));
        ItemsPanel.setMinimumSize(new java.awt.Dimension(140, 120));
        ItemsPanel.setPreferredSize(new java.awt.Dimension(140, 120));
        ItemsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ItemsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ItemsPanelMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(180, 16, 16));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Inventory");

        ItemsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Item.png"))); // NOI18N
        ItemsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemsIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ItemsIconMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout ItemsPanelLayout = new javax.swing.GroupLayout(ItemsPanel);
        ItemsPanel.setLayout(ItemsPanelLayout);
        ItemsPanelLayout.setHorizontalGroup(
            ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ItemsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ItemsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        ItemsPanelLayout.setVerticalGroup(
            ItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ItemsIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap())
        );

        LogoutPanel.setBackground(java.awt.SystemColor.controlHighlight);
        LogoutPanel.setMaximumSize(new java.awt.Dimension(140, 120));
        LogoutPanel.setMinimumSize(new java.awt.Dimension(140, 120));
        LogoutPanel.setPreferredSize(new java.awt.Dimension(140, 120));
        LogoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseExited(evt);
            }
        });

        LogoutIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Logout.png"))); // NOI18N
        LogoutIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutIconMouseEntered(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(180, 16, 16));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Logout");

        javax.swing.GroupLayout LogoutPanelLayout = new javax.swing.GroupLayout(LogoutPanel);
        LogoutPanel.setLayout(LogoutPanelLayout);
        LogoutPanelLayout.setHorizontalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LogoutPanelLayout.setVerticalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LogoutIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addContainerGap())
        );

        AddItemPanel.setBackground(java.awt.SystemColor.controlHighlight);
        AddItemPanel.setMaximumSize(new java.awt.Dimension(140, 120));
        AddItemPanel.setMinimumSize(new java.awt.Dimension(140, 120));
        AddItemPanel.setPreferredSize(new java.awt.Dimension(140, 120));
        AddItemPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddItemPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddItemPanelMouseExited(evt);
            }
        });

        AddItemIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddItemIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add Item.png"))); // NOI18N
        AddItemIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddItemIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddItemIconMouseEntered(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(180, 16, 16));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Add Item");

        javax.swing.GroupLayout AddItemPanelLayout = new javax.swing.GroupLayout(AddItemPanel);
        AddItemPanel.setLayout(AddItemPanelLayout);
        AddItemPanelLayout.setHorizontalGroup(
            AddItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddItemIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddItemPanelLayout.setVerticalGroup(
            AddItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddItemPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(AddItemIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addContainerGap())
        );

        UserManagementPanel.setBackground(java.awt.SystemColor.controlHighlight);
        UserManagementPanel.setMaximumSize(new java.awt.Dimension(140, 120));
        UserManagementPanel.setMinimumSize(new java.awt.Dimension(140, 120));
        UserManagementPanel.setPreferredSize(new java.awt.Dimension(140, 120));
        UserManagementPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserManagementPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserManagementPanelMouseExited(evt);
            }
        });

        UserManagementIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserManagementIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User Management.png"))); // NOI18N
        UserManagementIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserManagementIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserManagementIconMouseEntered(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(180, 16, 16));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("User Management");

        javax.swing.GroupLayout UserManagementPanelLayout = new javax.swing.GroupLayout(UserManagementPanel);
        UserManagementPanel.setLayout(UserManagementPanelLayout);
        UserManagementPanelLayout.setHorizontalGroup(
            UserManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserManagementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserManagementIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        UserManagementPanelLayout.setVerticalGroup(
            UserManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserManagementPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(UserManagementIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addContainerGap())
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(LogoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(ItemsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(AddItemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(UserManagementPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(583, 583, 583))))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddItemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserManagementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LogoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1166, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserManagementPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserManagementPanelMouseExited
        resetColor(UserManagementPanel);
    }//GEN-LAST:event_UserManagementPanelMouseExited

    private void UserManagementPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserManagementPanelMouseEntered
        setColor(UserManagementPanel);
    }//GEN-LAST:event_UserManagementPanelMouseEntered

    private void UserManagementIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserManagementIconMouseEntered
        setColor(UserManagementPanel);
    }//GEN-LAST:event_UserManagementIconMouseEntered

    private void UserManagementIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserManagementIconMouseClicked
        new UserManagement().show();
        dispose();
    }//GEN-LAST:event_UserManagementIconMouseClicked

    private void AddItemPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddItemPanelMouseExited
        resetColor(AddItemPanel);
    }//GEN-LAST:event_AddItemPanelMouseExited

    private void AddItemPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddItemPanelMouseEntered
        setColor(AddItemPanel);
    }//GEN-LAST:event_AddItemPanelMouseEntered

    private void AddItemIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddItemIconMouseEntered
        setColor(AddItemPanel);
    }//GEN-LAST:event_AddItemIconMouseEntered

    private void AddItemIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddItemIconMouseClicked
        new AddItem().show();
        dispose();
    }//GEN-LAST:event_AddItemIconMouseClicked

    private void LogoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseExited
        resetColor(LogoutPanel);
    }//GEN-LAST:event_LogoutPanelMouseExited

    private void LogoutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseEntered
        setColor(LogoutPanel);
    }//GEN-LAST:event_LogoutPanelMouseEntered

    private void LogoutIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutIconMouseEntered
        setColor(LogoutPanel);
    }//GEN-LAST:event_LogoutIconMouseEntered

    private void LogoutIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutIconMouseClicked
        new LoginForm().show();
        dispose();
    }//GEN-LAST:event_LogoutIconMouseClicked

    private void ItemsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemsPanelMouseExited
        resetColor(ItemsPanel);
    }//GEN-LAST:event_ItemsPanelMouseExited

    private void ItemsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemsPanelMouseEntered
        setColor(ItemsPanel);
    }//GEN-LAST:event_ItemsPanelMouseEntered

    private void ItemsIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemsIconMouseEntered
        setColor(ItemsPanel);
    }//GEN-LAST:event_ItemsIconMouseEntered

    private void ItemsIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemsIconMouseClicked
        new Inventory().show();
        dispose();
    }//GEN-LAST:event_ItemsIconMouseClicked

    private void HeaderPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPanelMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_HeaderPanelMousePressed

    private void HeaderPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_HeaderPanelMouseDragged
    int xx,xy;
    
    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(197, 197, 197));
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(240,240,240));
    }

    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Home().setVisible(true);
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddItemIcon;
    private javax.swing.JPanel AddItemPanel;
    private javax.swing.JLabel DisplayUserLogin;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel ItemsIcon;
    private javax.swing.JPanel ItemsPanel;
    private javax.swing.JLabel LogoutIcon;
    private javax.swing.JPanel LogoutPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel UserManagementIcon;
    private javax.swing.JPanel UserManagementPanel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    // End of variables declaration//GEN-END:variables

    
}
